---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: classification-deployment
   labels:
     app: classification
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: classification
   template:
     metadata:
       labels:
         app: classification
     spec:
       containers:
         - name: keras-classification
           image: kubacrjw.azurecr.io/keras-classification:v1
           ports:
             - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: classification-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: classification